# Generated by Django 5.1.2 on 2024-11-08 17:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EventOutbox",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=255)),
                (
                    "event_date_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("environment", models.CharField(max_length=255)),
                ("event_context", models.JSONField()),
                ("metadata_version", models.IntegerField(default=1)),
                ("processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "event_outbox",
            },
        ),
    ]
